---
- name: Create database
  mysql_db:
    login_user: "{{ item.value.priv_user }}"
    login_password: "{{ item.value.priv_password }}"
    login_host: "{{ item.value.host.split(':')[0] }}"
    name: "{{ item.value.name }}"
    state: present
  when:
    - grafana_privileges_credential is defined
  with_dict: >
    {{ grafana_database_config | combine(grafana_privileges_credential|default({}), recursive=True) }}

- name: Grant access to the DB
  mysql_user:
    login_user: "{{ item.0.priv_user }}"
    login_password: "{{ item.0.priv_password }}"
    login_host: "{{ item.0.host.split(':')[0] }}"
    name: "{{ item.0.user }}"
    password: "{{ item.0.password }}"
    host: "{{ item.1 }}"
    state: present
    priv: "{{ item.0.name }}.*:ALL"
  when:
    - grafana_privileges_credential is defined
  with_subelements:
    - "{{ grafana_database_config | combine(grafana_privileges_credential|default({}), recursive=True) }}"
    - priv_host
    - skip_missing: yes
