---
- name: Install grafana packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ grafana_apt_package }}"
    - "{{ grafana_apt_dependencies }}"

- name: Ensure {{ grafana_service_name }} service started and start up at boot
  service:
    name: "{{ grafana_service_name }}"
    state: started
    enabled: yes
    daemon_reload: yes
