---
- name: Add influxdb repository key
  apt_key:
    url: "{{ influxdb_apt_key_url }}"

- name: Add influxdb apt-repository
  apt_repository:
    repo: "{{ influxdb_apt_repo }}"

- name: Install required python influxdb library
  apt:
    name: python3-influxdb
    state: present
    update_cache: yes
